version: '3'

services:
  postgres:
    image: postgres:13.4-alpine
    ports:
      - 5402:5432
    environment:
      POSTGRES_PASSWORD: pg-password
      POSTGRES_USER: pg-user
      POSTGRES_DB: local_quarterback_db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - 5380:6379
    volumes:
      - ./db/redis:/var/lib/redis/data

networks:
  default:
    name: quarterback-local