version: '3.7'

services:
  postgres:
    image: postgres:13.4-alpine
    ports:
      - 5402:5432
    environment:
      POSTGRES_PASSWORD: pg-password
      POSTGRES_USER: pg-user
      POSTGRES_DB: local_quarterback_db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

networks:
  default:
    name: quarterback-local