version: '3'

services:
  api:
    build:
      context: .
      dockerfile: quarterback-packages/api/Dockerfile
    ports:
      - 7500:7500
    environment:
      NODE_ENV: production
      PORT: 7500
      LOG_LEVEL: info
      JWT_SECRET: verylongrandomstring
      DATABASE_URL: postgresql://pg-user:pg-password@host.docker.internal:5402/local_quarterback_db?schema=public
    restart: always
  postgres:
    image: postgres:13.4-alpine
    ports:
      - 5402:5432
    environment:
      POSTGRES_PASSWORD: pg-password
      POSTGRES_USER: pg-user
      POSTGRES_DB: local_quarterback_db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - 5380:6379
    volumes:
      - ./db/redis:/var/lib/redis/data

networks:
  default:
    name: quarterback-local
