name: 'pnpm installation'
description: 'Install and audit dependencies for pnpm'
inputs:
  cache: # id of input
    description: 'The location of the pnpm cache'
    required: true
    default: '.pnpm-store'

runs:
  using: 'composite'
  steps:
    - name: install pnpm
      run: npm i pnpm@7.30.5 -g
      shell: bash

    - name: setup pnpm config
      run: pnpm config set store-dir ${{ inputs.cache }}
      shell: bash

    - name: install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
